### ISSUE TITLE
Distance not calculated correctly

### ISSUE THREAD

**Issue by joernba** [objectivehtml/Google-Maps-for-Craft#31]
I'm trying to get the distance search to work with the 8.3.0 release of the plugin. I used version 7.3.0 and everything worked fine. After upgrading the distance is not calculated correctly anymore. I use this code:
```
{% set query = craft.request.getParam('q') %}

  {% set params = {
      address: query,
      distance: 100
  } %}

  {% set entries = craft.entries.section('storeLocator').map(params).order('distance asc') %}

```
I get results that are just not correct. I can't actually find a real pattern (there might be one).

**Comment by objectivehtml** [comment]
Can you download the master branch? It should fix this issue.

**Comment by joernba** [comment]
Seems to work. Thank you very much!
