### ISSUE TITLE
Distance to author

### ISSUE THREAD

**Issue by johanneslamers** [objectivehtml/Google-Maps-for-Craft#33]
Hi @objectivehtml 

Is it possible to show the distance between the visitor and the author in KM in an entry?

The author of the entry has some address fields you can use to calculate (zipcode, address, city)

**Comment by objectivehtml** [comment]
I just added this in the most recent build. Here is my template code using "kilometers". You can also enter "kilometres" or "km".

    {% set query = craft.request.getParam('q') %}

    {% set params = {
        address: query,
        distance: 200,
        unit: 'kilometers'
    } %}

    {% set options = {
        id: 'map', 
        width: '400px', 
        height: '300px',
        clustering: true
    } %}

    {{ craft.googleMaps.map(options) }}

    <ul class="search-results">
    {% set entries = craft.entries.section('news').map(params).order('distance asc') %}
    {% for entry in entries %}
        <li>
            <h3>{{ entry.title }}</h3>
            
            {{ craft.googleMaps.data('map', entry.map) }}

            {% for marker in entry.map.markers() %}
                <p>Distance - {{ marker.distance }}</p>
            {% endfor %}
        </li>
    {% endfor %}
    </ul>
