### ISSUE TITLE
Property "Craft\GoogleMaps_GoogleMapFieldType._results" is not defined

### ISSUE THREAD

**Issue by neilbradley** [objectivehtml/Google-Maps-for-Craft#34]
Updated the plugin in Craft to the latest version here and my admin shows the following error;
Property "Craft\GoogleMaps_GoogleMapFieldType._results" is not defined.

/craft/plugins/googlemaps/fieldtypes/GoogleMaps_GoogleMapFieldType.php(16)

$t->_results[$event->params['element']->id] = $event->params['result'];

**Comment by objectivehtml** [comment]
Can you open the file and change "private" to "protected" on line 8? If none of that works, try using "public". I don't get this error with my version of PHP, so I think it's something to do with an older version of PHP.

**Comment by neilbradley** [comment]
Hi,
Changing to 'public' got it working. I'm using PHP Version 5.3.24.

**Comment by objectivehtml** [comment]
Ok, thanks I will get this fixed.
