### ISSUE TITLE
Internal Server Error; Property "Craft\GoogleMaps_GoogleMapFieldType._results" is not defined

### ISSUE THREAD

**Issue by MattWilcox** [objectivehtml/Google-Maps-for-Craft#35]
I've got it all installed and working on a local Craft project, but upon checking the project out onto to a staging server (via SVN - all the files are identical and its using the same database) the staging server version craps out with that message on any front-end template that attempts to use the field type.

The local version is in Dev mode, the staging version is not. Other than that, there should be no difference in server environment.

**Comment by objectivehtml** [comment]
I am looking into this, but I am not seeing this error locally. On which line is this error being thrown? Also, what PHP version are you using on staging?

Here is the code in question. You can see in my version, that $_results is defined. I am just wondering if accessing "$this" inside the closure with a private method is causing you issues on your staging server but not locally.

    private $_results = array();

    public function init()
    {
        $t = $this;

        craft()->on('elements.populateElement', function(Event $event) use ($t)
        {
            $t->_results[$event->params['element']->id] = $event->params['result'];
        });
    }

**Comment by MattWilcox** [comment]
Hi there,

thanks for looking into this. There is no error line number shown; the error that's shown is the simple Craft white 'modal' box that's centered in a grey page. No other details available.

The staging server is running Debian 6, and PHP 5.3.3-7+squeeze19 with Suhosin-Patch (cli) (built: Feb 17 2014 10:10:23)

**Comment by objectivehtml** [comment]
Can you try to change the word "private" to "public" (for the $_results property) to see if that fixes the issue? I am almost certain this has to do with your PHP version, because I don't get this error on my end using PHP 5.5.x.

**Comment by objectivehtml** [comment]
You can also check the craft.log file, that should give you the line number for that error. I am pretty sure what line it is though.

**Comment by MattWilcox** [comment]
That fixed it, thanks very much!

I need to look into updating our staging server...
