### ISSUE TITLE
Pull extract from marker.address

### ISSUE THREAD

**Issue by niallthompson** [objectivehtml/Google-Maps-for-Craft#38]
Using {{ marker.address }} in my template is there a way to just get the city or locality?

For example: London or Los Angeles.

This is my current markup:

`{% for marker in entry.location.getMarkers() %}{{ marker.address }}{% endfor %}`

**Comment by Jammooka** [comment]
You can use marker.addressComponents instead.

Output `{{ dump(marker.addressComponents) }}` and you'll see the full array.

In your particular case, you'd probably have to do something like:
```
{% for part in marker.addressComponents %}
	{% if part.types[0] == 'postal_town' %}{{ part.long_name }}{% endif %}
{% endfor %}
```

**Comment by objectivehtml** [comment]
Just for reference, you can also use `{{ marker.formattedAddress }}`.
