### ISSUE TITLE
Keep map centred when browser window size changes

### ISSUE THREAD

**Issue by katrinkerber** [objectivehtml/Google-Maps-for-Craft#40]
What's the best way to make use of [this solution](http://hsmoore.com/keep-google-map-v3-centered-when-browser-is-resized/), which keeps the map centred when the browser window size changes?

**Comment by objectivehtml** [comment]
I know this is super old, but I ended up having some health issues and didn't work most of last year. I'm back now though and figured I would post the solution to this for future reference.

	{% set options = {
		id: 'map', 
		width: '100%', 
		height: '100%',
		center: 'The Florida Keys'
	} %}

	{{ craft.googleMaps.map(options) }}

	<script type="text/javascript">
		var mapCenter;

		window.onload = function() {
			mapCenter = map.getCenter();
		};
		
		window.onresize = function(e) {
			map.setCenter(mapCenter.lat(), mapCenter.lng());
		};

	</script>
