### ISSUE TITLE
geocoded data only lands in craft_googlemaps_locations on editing the entry, not when creating the entry

### ISSUE THREAD

**Issue by flowcomm** [objectivehtml/Google-Maps-for-Craft#44]
When creating a new entry (using the geocoding service based on longitude and latitude fields)

The geocoding service fires and stores the data in craft_googlemaps_geocoder_cache and also as Json in the craft content entries table (under the correct field)

However, the data does not get saved to craft_googlemaps_locations. 

Only when I edit (using the exact same form) and save again, does the location get saved into craft_googlemaps_locations

This occurs on both my front end form, and the backend for me. 

Thanks,
Richard

**Comment by objectivehtml** [comment]
Sorry for the long reply on this. I was out a lot of last year with some serious health and personal issues. Finally coming back around and getting caught up.

I am not able to duplicate this issue locally at all. If you are still having issues with this feel free to post back. I know this was a super long time ago so I don't expect you, rather just wanted to reply back for others reading or in case you were still wondering. In any case, i'm back to updating and supporting this plugin again so you can look to see changes and updates in the future.
