### ISSUE TITLE
Folder Name

### ISSUE THREAD

**Issue by kaspar-allenbach** [objectivehtml/Google-Maps-for-Craft#49]
You plugin doesn't appear in the Control Panel. I guess because your plugin folder has the wrong syntax. How should I rename it?

**Comment by madebyshape** [comment]
Just had this issue also. Just rename the folder to "googlemaps"

**Comment by objectivehtml** [comment]
Due to the nature and structure of the git repo, you have to basically create the `googlemaps` directory and then clone the repo to it, or unzip your files there.

https://github.com/objectivehtml/Google-Maps-for-Craft/wiki/Installation
