### ISSUE TITLE
Polgyon Color Options

### ISSUE THREAD

**Issue by BryanBelanger** [objectivehtml/Google-Maps-for-Craft#50]
I've created a map with several markers and a polygon. I've tried to set and change the fillColor and strokeColor options by following the wiki. 

{{ craft.googleMaps.polygon('map', points, {strokeColor: '#ff0000}) }}

Above is an example of how I'm currently doing it. Has anyone else run into issues where you can not set the strokeColor or fillColor and it just defaults to black?

**Comment by cameronwest** [comment]
I've fixed this issue in an outstanding pull request:

https://github.com/objectivehtml/Google-Maps-for-Craft/pull/41

**Comment by objectivehtml** [comment]
Fixed and merged into the master branch. Closing this thread. Thanks for the help guys.
