### ISSUE TITLE
Force search within specific country

### ISSUE THREAD

**Issue by neilbradley** [objectivehtml/Google-Maps-for-Craft#51]
Hi,
In the ExpressionEngine version, there is the option to add the following hidden field to a search form to always search within a specific country:

 `<input type="hidden" name="country" value=", UK" />`

Is something similar possible with the Craft version?

**Comment by objectivehtml** [comment]
Hey man, sorry for the delay. I was out most of last year with health issues but back in action now.

		{% set query = craft.request.getParam('q') %}

		{% set params = {
			address: query ~ ', UK',
			distance: 200
		} %}
